### ISSUE TITLE
Profile setting does not seem to work

### ISSUE THREAD

**Issue by Tokn59** [flyjmz/jmzSmartThings#4]
Hello, I have the option set in Blue Iris to only trigger "Only when mode is" set to "Away". However this does not seem to work. Logging shows this : 

a6a7f7df-a58a-4170-8a13-7c7930ff220b  18:14:12: debug serverOfflineChecker() found server response time was 0.347
a6a7f7df-a58a-4170-8a13-7c7930ff220b  18:14:12: debug serverOfflineChecker() has state.hubCommandReceivedTime at 1523636047790 and state.hubCommandSentTime at 1523636047443
a6a7f7df-a58a-4170-8a13-7c7930ff220b  18:14:12: debug serverOfflineChecker() found server response time was 0.347
a6a7f7df-a58a-4170-8a13-7c7930ff220b  18:14:12: debug serverOfflineChecker() has state.hubCommandReceivedTime at 1523636047790 and state.hubCommandSentTime at 1523636047443
**a6a7f7df-a58a-4170-8a13-7c7930ff220b  18:14:08: debug Profile Error Check: want 'Away' == 'Away' or 'Away' == false.**
a6a7f7df-a58a-4170-8a13-7c7930ff220b  18:14:08: info parsing results: profile is number '1' ('Away'), signal is 'green', lock is '2' ('Hold'), triggered camera is 'null'
a6a7f7df-a58a-4170-8a13-7c7930ff220b  18:14:08: debug getprofileName returning name Away
a6a7f7df-a58a-4170-8a13-7c7930ff220b  18:14:08: debug getprofileName got number 1
a6a7f7df-a58a-4170-8a13-7c7930ff220b  18:14:07: debug body: signal=green
profile=1
lock=2 
a6a7f7df-a58a-4170-8a13-7c7930ff220b  18:14:07: debug bodyList is '[signal=green, profile=1, lock=2]'
a6a7f7df-a58a-4170-8a13-7c7930ff220b  18:14:07: debug status: 200
a6a7f7df-a58a-4170-8a13-7c7930ff220b  18:14:07: debug headerMap: [content-length:31, http/1.1 200 ok:null, cache-control:no-cache, no-store, connection:Close, set-cookie:session=2b6934367f085a0b719e78ef7bb91deb; path=/, access-control-allow-origin:*, p3p:CP="CAO COR CURa ADMa DEVa OUR IND ONL COM DEM PRE", content-type:text/plain, date:Fri, 13 Apr 2018 16:14:08 GMT, server:BlueIris-HTTP/1.1]
a6a7f7df-a58a-4170-8a13-7c7930ff220b  18:14:07: debug headersAsString: HTTP/1.1 200 OK 

Is the bold section an indication ,of an error ? What is wrong ?

Thanks for your help !!!

Tony

**Comment by flyjmz** [comment]
Tony, what is the issue you are having? From your question, it sounds like you’re trying to use a trigger to make the camera record, but only want that to happen in away mode. Is it not triggering ever, or is it triggering all the time, or what specifically?

The part you bolded is just a debug line to aid folks when they are having issues. In your case, it shows that everything is ok. But a couple lines down from there it says the camera is ‘null.’  That is a problem. So I assume your problem is that the camera never triggers. Are you using the camera and server  DTHs? If so, make sure you set up the cameras first in BI Fusion settings, click done until you’re out of settings so that they are initialized, then go back into settings and set up the trigger you want. If you’re using the camera DTH, you can then just select the camera you want from the list instead of having to type in it’s shortname. Lemme know if that works or you’re still having issues

**Comment by flyjmz** [comment]
I'm assuming it's fixed since you didn't reply.  If not, let me know.
